Algoritmo "AREACIRCULO"
// Disciplina   : [Lógica de Programação com JavaSxript]
// Professor   :  Obama - indiano
// Descrição   : Calcula a area de um circulo
// Autor(a)    : Isaque de Oliveira Cruz
// Data atual  : 17/03/2023
Var
// Seção de Declarações das variáveis 
raio:real
area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor do raio:" )
leia(raio)
area<-PI*raio*raio
escreva("O valor da área é:",area)

Fimalgoritmo